#!/usr/bin/env ruby

# Set our root dir
$:.unshift(File.join(File.expand_path(File.dirname(__FILE__)), '.'))
$root_dir = File.expand_path('..', __FILE__)

# Load and bootstrap RubyCA
require 'core/load'
require 'core/bootstrap'

# Start server
if CONFIG['web']['port'] < 1024
  unless Process.euid == 0 
    puts "\nError: RubyCA is set to use port less than 1024. Need root access."
    puts "Root privileges will be dropped once the server bind port."
    puts "Please run RubyCA using 'sudo ./RubyCA' or change port in config file."
    abort
  end
end

RubyCA::Core::Web::Server.run!
puts ''