#!/usr/bin/env ruby

# Set our root dir
$:.unshift(File.join(File.expand_path(File.dirname(__FILE__)), '.'))
$root_dir = File.expand_path('..', __FILE__)

# Load and bootstrap RubyCA
require 'core/load'
require 'core/bootstrap'

# Configure and start Thin
rack_app = Rack::URLMap.new '/' => RubyCA::Core::Web::Manager,  '/test' => RubyCA::Core::Web::Manager
thin_server = Thin::Server.new CONFIG['web']['host'], CONFIG['web']['port'], rack_app
thin_server.start